# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mechthild Pieper
title: MSc Student in Management of Information Systems 
email: m.pieper02@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  Mecky4
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: mecky4
linkedin_username: mechthild-pieper-706597153
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Mecky and am currently in my last semester of Master Studies. 
  
  My study focus lies on Management of Information Systems and I am particularly interested in the social implications of the use of artificial intelligence in orgnaizations. 
  
  I am currently finishing my Master Thesis on human-AI-augmentation, while simultaneously learning how technology shapes and impacts our work-environments, society and lifes. 
  My goal is to keep conducting insightful and relevant research within these areas. 


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: WoMenInTech (WIT) Mannehim 
        link: https://wit-mannheim.webflow.io/
        # link_text: Initiative's Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This cool group of people are the reason why this amazing online CV of mine even exists! 
        description: | # this will include new lines to allow paragraphs
          In fall 2020 I became part of this great initiative, which together with an enthusiastic group of people we have been building up every since. During bi-weekly meetings we chat about all kinds of tech topics. 
          In addition we regularly invite inspiring speakers or hold small workshop, such as this one, where we learn to build our own online CV on GitHub. 

  - title: Experiences # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Institue for Enterprise Systems (InES)
        link: https://www.institute-for-enterprise-systems.de/
        # link_text: insititute-for-enterprise-systems.de
        sub_title: Research Assistant
        caption: 5 months
       # quote: >
       #   [Cloud Mall Baden-Württemberg9](https://cloud-mall-bw.de/)
        description: | # this will include new lines to allow paragraphs
          Working on a collaboration project for Cloud Computing cooperations with a focus on Artifical Intelligence development, implementation, and usage. 
        [Cloud Mall Baden-Württemberg](https://cloud-mall-bw.de/)
        
  
      - layout: left
        title: Lufthansa Cargo AG (LCAG)
        link: https://lufthansa-cargo.com/
        # link_text: lufthansa-cargo.com
        sub_title: Supply Chain Management Intern
        caption: 3 months
        #quote: >
        #  In the area of Global Handling at Frankfurt am Main 
        description: | # this will include new lines to allow paragraphs
          In the area of Global Handling at Frankfurt am Main
          Supporting software tests for the development and implementation of the IT-project "Product Planning and Steering", as well as conducting Supply Chain Management analysis for the global hubs of the LCAG.
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Copenhagen Business School
        caption: 2021 - 2022
        sub_title: MSc Business Administration and Information Systems
        quote: >
          Double Degree Program with the University of Mannheim and Copenhagen Business School that provides the best of both worlds and a truly international experience.
        description: | # this will include new lines to allow paragraphs
          During my year at CBS I strongly shifted my focus towards the management of technology within organizations, complemented with practical programming courses in Data Science and Machine Learning. 
          
          Meanwhile I conducted qualitative research for my master thesis concerned with human-AI-augmentation and the question "How AI can augment human decision-making, if the corresponding AI is supposed to learn form the decsision maker?"
      
      - layout: left
        title: University of Mannheim
        caption: 2020 - 2021
        sub_title: MSc Mannheim Master in Management 
        quote: >
          Double Degree Program with the University of Mannheim and Copenhagen Business School that provides the best of both worlds and a truly international experience.
        description: | # this will include new lines to allow paragraphs
          During my first year of Master studies, I enjoyed a broader sientific and economic education that layed the foundation for all following undertakings. 
          Courses such as Business Economics, Decision Analysis or Theories and (Empirical) Methods provided my the right tools and knowledge to focus on more specific issues and topics, such as Business Intelligence, Adaptaive Systems Management or IT-Project Complexities.
          
      - layout: left
        title: University of Cologne 
        caption: 2015 - 2019
        sub_title: BSc Business Administration and Supply Chain Management 
        quote: >
          A three year Bachelor Programm in one of the coolest cities in the world !  
        description: | # this will include new lines to allow paragraphs
          I did my bachelors in Cologne, where i received the foundations in Business Adminsitration and Management, as well as economics and social science. First my interest were drawn towards logisitcs and supply chain management. 
          Through international experiences and internships, I shifted towards analytics and data science, and thus decided to follow up the bachelors with a Master in Information Systems and IT Management. 
      
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in research and technology's social impact some of my other interests and hobbies are:
      - Travelig (all around the world)
      - Sports (Running, Climbing, Tennis)
      - Music (I play the harp!) 
      - [Baking Videos, because they can be very relaxing](https://www.youtube.com/watch?v=CZrVmK2kyFQ)

     # Look at this cool image  
     # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
references_title: Built with Matt Sproogen's Modern Resume Theme (https://github.com/sproogen/modern-resume-theme)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
